import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div>
          <span>.avif</span>
          <Image
            src='/images/sample.avif'
            alt='Sample Image'
            width={500}
            height={325}
          />
        </div>
        <div>
          <span>.gif</span>
          <Image
            // unoptimized={true}
            src='/images/sample.gif'
            alt='Sample Image'
            width={500}
            height={325}
          />
        </div>
        <div>
          <span>.jpeg</span>
          <Image
            src='/images/sample.jpg'
            alt='Sample Image'
            width={500}
            height={325}
          />
        </div>
        <div>
          <span>.png</span>
          <Image
            src='/images/sample.png'
            alt='Sample Image'
            width={500}
            height={325}
          />
        </div>
        <div>
          <span>.webp</span>
          <Image
            src='/images/sample.webp'
            alt='Sample Image'
            width={500}
            height={325}
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
